---
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.2
services:
  - mysql
  - postgresql
sudo: required
env:
  - PDNS_ARGS="--config-dir=/tmp" DB=mysql
  - PDNS_ARGS="--config-dir=/tmp" DB=pgsql
before_script:
  - wget https://downloads.powerdns.com/releases/deb/pdns-static_3.4.7-1_amd64.deb && sudo dpkg -i pdns-static_3.4.7-1_amd64.deb
  - ./travis/pdns.sh
  - ./travis/smart-proxy.sh
cache: bundler
script: bundle exec rake test:all
