---
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.2
services:
  - mysql
  - postgresql
sudo: required
dist: trusty
env:
  - PDNS_ARGS="--config-dir=/tmp" DB=mysql
  - PDNS_ARGS="--config-dir=/tmp" DB=pgsql
before_script:
  - curl https://repo.powerdns.com/CBC8B383-pub.asc | sudo apt-key add - && echo 'deb http://repo.powerdns.com/ubuntu trusty-auth-master main' | sudo tee -a /etc/apt/sources.list && sudo apt-get update
  - sudo apt-get install -y pdns-server pdns-backend-mysql pdns-backend-pgsql
  - ./travis/pdns.sh
  - ./travis/smart-proxy.sh
cache: bundler
script: bundle exec rake test:all
